### ISSUE TITLE
How can I rotate my camera card?

### ISSUE THREAD

**Issue by TheGreatBorg** [pinkywafer/octoprint-HA#1]
First I really like your octoprint config. But how can I rotate my camera image? I have tried with style and transform: rotate(90deg) but it doesn't seems to work. Do you have suggestions?

![image](https://user-images.githubusercontent.com/31419036/72661948-e5423380-39e0-11ea-8c0d-72548f31a231.png)

**Comment by pinkywafer** [comment]
Assuming you're using the raspberry pi camera, The best option is to configure the rotation on the raspberry pi running octoprint...
Either on the pi itself, or via ssh or by putting the SD card into another computer. 
Edit the /boot/octopi.txt file.
Find : `camera_raspi_options`
And add this option: `-rot 90`

Should do the trick! 🤞

**Comment by TheGreatBorg** [comment]
This actually solved my problem: https://github.com/thomasloven/lovelace-card-mod
![image](https://user-images.githubusercontent.com/31419036/72668119-c3b66b80-3a23-11ea-9440-db8896fd03f1.png)

![image](https://user-images.githubusercontent.com/31419036/72668127-d29d1e00-3a23-11ea-962c-9ec62aba1c10.png)

**Comment by pinkywafer** [comment]
That's fine as long as you aren't using the mjpeg stream for anything else...  any other connection would still show the image at the wrong orientation

**Comment by TheGreatBorg** [comment]
Yep that's right - but changing octopi.txt doesn't seem to have effect. I have tried with this:

![image](https://user-images.githubusercontent.com/31419036/72668710-f19eae80-3a29-11ea-9a82-2071a5caf39d.png)

**Comment by pinkywafer** [comment]
Ahh... that's the issue, you're using a USB camera, and I believe the `-rot` in octopi.txt only works for a pi camera. So I can't think of a better solution than using the card-mod as you are doing
